FROM php:8.1.10-fpm-alpine3.16

RUN apk add --no-cache openssl bash vim mysql-client icu-dev

RUN docker-php-ext-configure intl && docker-php-ext-install intl

RUN docker-php-ext-install pdo pdo_mysql bcmath mysqli intl \
    && docker-php-ext-enable pdo_mysql

RUN adduser -D www 

USER www
WORKDIR /var/www/

CMD php artisan serve --host=0.0.0.0 --port=8080
EXPOSE 8080